#!/bin/bash

echo "🔗 Setting up Stripe Webhook"
echo ""
echo "I've opened the Stripe Webhooks page in your browser."
echo ""
echo "Follow these steps:"
echo ""
echo "1. Click 'Add endpoint' button"
echo ""
echo "2. Enter this URL:"
echo "   https://getekqgyhwmbhyznamli.supabase.co/functions/v1/stripe-webhook"
echo ""
echo "3. Select these events:"
echo "   - checkout.session.completed"
echo "   - customer.subscription.updated"
echo "   - customer.subscription.deleted"
echo "   - invoice.payment_succeeded"
echo "   - invoice.payment_failed"
echo ""
echo "4. Click 'Add endpoint'"
echo ""
echo "5. Click on the newly created endpoint"
echo ""
echo "6. Find 'Signing secret' (starts with whsec_)"
echo ""
echo "7. Copy the signing secret"
echo ""
read -p "Press Enter when you have the signing secret copied..."
echo ""
echo "8. Now go to Supabase Edge Functions Secrets:"
echo "   https://supabase.com/dashboard/project/getekqgyhwmbhyznamli/settings/functions"
echo ""
echo "9. Add a new secret:"
echo "   Name: STRIPE_WEBHOOK_SECRET"
echo "   Value: [paste your whsec_... secret]"
echo ""
read -p "Press Enter when you've added the secret..."
echo ""
echo "✅ Webhook setup complete!"
echo ""
echo "🎉 Everything is ready! Now test it:"
echo "   1. Go to http://localhost:3000/"
echo "   2. Sign up / log in"
echo "   3. Try to upgrade to Entrepreneur plan"
echo "   4. Complete the Stripe checkout"
echo ""
