#!/bin/bash

echo "🔐 Setting up Supabase Edge Function Secrets"
echo ""
echo "I've opened the secrets page in your browser."
echo ""
echo "Add these 3 secrets (click 'Add new secret' for each):"
echo ""
echo "1. Name: STRIPE_SECRET_KEY"
echo "   Value: [Your Stripe secret key from Stripe dashboard - sk_...]"
echo ""
echo "2. Name: SUPABASE_URL"
echo "   Value: https://getekqgyhwmbhyznamli.supabase.co"
echo ""
echo "3. Name: SUPABASE_SERVICE_ROLE_KEY"
echo "   Value: [Your service role key from Supabase API settings]"
echo ""
echo "Note: We'll add STRIPE_WEBHOOK_SECRET after deploying functions"
echo ""
read -p "Press Enter when you've added all 3 secrets..."
echo ""
echo "✅ Great! Now let's deploy the functions..."
