#!/bin/bash

echo "========================================="
echo "Subscription Fix Verification Script"
echo "========================================="
echo ""

# Check if user is logged in to Supabase
echo "1. Checking Supabase connection..."
supabase projects list > /dev/null 2>&1
if [ $? -eq 0 ]; then
    echo "   ✅ Connected to Supabase"
else
    echo "   ❌ Not connected to Supabase. Run: supabase login"
    exit 1
fi

echo ""
echo "2. Deployed Edge Functions:"
supabase functions list | grep -E "stripe-webhook|create-checkout-session"

echo ""
echo "========================================="
echo "What was fixed:"
echo "========================================="
echo "1. ✅ Added price ID to plan name mapping"
echo "2. ✅ Updated checkout.session.completed handler"
echo "3. ✅ Updated customer.subscription.updated handler"
echo "4. ✅ Added proper logging for debugging"
echo "5. ✅ Added unique constraint for upsert operations"
echo ""

echo "========================================="
echo "Next Steps to Apply Database Migration:"
echo "========================================="
echo "1. Go to your Supabase Dashboard"
echo "2. Navigate to SQL Editor"
echo "3. Run the migration file: supabase/migrations/002_fix_subscriptions_upsert.sql"
echo ""
echo "The migration adds:"
echo "   - Unique constraint on stripe_subscription_id"
echo "   - Unique index on (user_id, stripe_subscription_id)"
echo ""

echo "========================================="
echo "Testing the Fix:"
echo "========================================="
echo "1. Make a test subscription through your app"
echo "2. After successful payment, check:"
echo "   - User profile subscription_tier should update to 'entrepreneur'"
echo "   - Subscriptions table should have the correct entry"
echo ""
echo "3. Monitor webhook logs in Supabase Dashboard:"
echo "   Functions > stripe-webhook > Logs"
echo ""
echo "   Look for these log messages:"
echo "   - 'Subscription details' with priceId and planName"
echo "   - 'Successfully updated user to {plan} plan'"
echo ""

echo "========================================="
echo "Troubleshooting:"
echo "========================================="
echo "If subscription still doesn't update:"
echo ""
echo "1. Verify webhook secret is set:"
echo "   supabase secrets list"
echo "   Should see: STRIPE_WEBHOOK_SECRET"
echo ""
echo "2. Check Stripe webhook configuration:"
echo "   - Endpoint URL should point to your Supabase function"
echo "   - Should listen for: checkout.session.completed"
echo ""
echo "3. Verify price IDs match in both files:"
echo "   - lib/stripe.ts"
echo "   - supabase/functions/stripe-webhook/index.ts"
echo ""
echo "Current price IDs configured:"
echo "   free:         price_1SOM6aDPosqqbsKxdrWWe834"
echo "   entrepreneur: price_1SOM7DDPosqqbsKx8lBviJSS"
echo ""

echo "========================================="
echo "Manual Database Check (Optional):"
echo "========================================="
echo "Run these queries in Supabase SQL Editor:"
echo ""
echo "-- Check user profile tier"
echo "SELECT id, subscription_tier, stripe_customer_id"
echo "FROM user_profiles"
echo "WHERE id = 'YOUR_USER_ID';"
echo ""
echo "-- Check subscriptions"
echo "SELECT user_id, plan_name, status, stripe_price_id"
echo "FROM subscriptions"
echo "WHERE user_id = 'YOUR_USER_ID';"
echo ""
