#!/bin/bash

echo "🔍 Checking if database tables were created..."
echo ""
echo "Please check your Supabase Dashboard:"
echo "👉 https://supabase.com/dashboard/project/getekqgyhwmbhyznamli/editor"
echo ""
echo "You should see these tables:"
echo "  ✓ user_profiles"
echo "  ✓ subscriptions"
echo ""
echo "If you see both tables, the migration worked! 🎉"
echo ""
echo "Next steps:"
echo "1. Close and reopen your browser tab at http://localhost:3000/"
echo "2. Hard refresh (Cmd+Shift+R)"
echo "3. Try creating an account or generating hustles"
echo "4. The 'Failed to fetch' error should be gone!"
echo ""
